# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'designs/mw_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(851, 660)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("designs\\../img/Без названия.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setWindowOpacity(1.0)
        MainWindow.setStyleSheet("background-color: #333333;")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label.setStyleSheet("color: #ffffff;")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_2.setStyleSheet("color: #ffffff;")
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 2, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_3.setStyleSheet("color: #ffffff;")
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 4, 1, 1)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setStyleSheet("background-color: #000000;")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 1, 0, 1, 5)
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setStyleSheet("background-color: #000000;")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.gridLayout.addWidget(self.line_2, 0, 1, 1, 1)
        self.line_5 = QtWidgets.QFrame(self.centralwidget)
        self.line_5.setStyleSheet("background-color: #000000;")
        self.line_5.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.gridLayout.addWidget(self.line_5, 0, 3, 1, 1)
        self.scrollArea_3 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_3.setStyleSheet("background-color: #444444;")
        self.scrollArea_3.setLineWidth(0)
        self.scrollArea_3.setWidgetResizable(True)
        self.scrollArea_3.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_3.setObjectName("scrollArea_3")
        self.scrollAreaWidgetContents_6 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_6.setGeometry(QtCore.QRect(0, 0, 265, 589))
        self.scrollAreaWidgetContents_6.setObjectName("scrollAreaWidgetContents_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doneLayout = QtWidgets.QVBoxLayout()
        self.doneLayout.setSpacing(0)
        self.doneLayout.setObjectName("doneLayout")
        self.horizontalLayout_2.addLayout(self.doneLayout)
        self.scrollArea_3.setWidget(self.scrollAreaWidgetContents_6)
        self.gridLayout.addWidget(self.scrollArea_3, 2, 4, 2, 1)
        self.scrollArea_2 = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea_2.setStyleSheet("background-color: #444444;")
        self.scrollArea_2.setLineWidth(0)
        self.scrollArea_2.setWidgetResizable(True)
        self.scrollArea_2.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea_2.setObjectName("scrollArea_2")
        self.scrollAreaWidgetContents_5 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_5.setGeometry(QtCore.QRect(0, 0, 265, 589))
        self.scrollAreaWidgetContents_5.setObjectName("scrollAreaWidgetContents_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.scrollAreaWidgetContents_5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.progressLayout = QtWidgets.QVBoxLayout()
        self.progressLayout.setSpacing(0)
        self.progressLayout.setObjectName("progressLayout")
        self.horizontalLayout_3.addLayout(self.progressLayout)
        self.scrollArea_2.setWidget(self.scrollAreaWidgetContents_5)
        self.gridLayout.addWidget(self.scrollArea_2, 2, 2, 2, 1)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setStyleSheet("background-color: #444444;")
        self.scrollArea.setLineWidth(0)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setAlignment(QtCore.Qt.AlignCenter)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_4 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_4.setGeometry(QtCore.QRect(0, 0, 265, 589))
        self.scrollAreaWidgetContents_4.setObjectName("scrollAreaWidgetContents_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_4)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.toDoLayout = QtWidgets.QVBoxLayout()
        self.toDoLayout.setSpacing(0)
        self.toDoLayout.setObjectName("toDoLayout")
        self.verticalLayout_2.addLayout(self.toDoLayout)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents_4)
        self.gridLayout.addWidget(self.scrollArea, 2, 0, 2, 1)
        self.line_4 = QtWidgets.QFrame(self.centralwidget)
        self.line_4.setStyleSheet("background-color: #000000;")
        self.line_4.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.gridLayout.addWidget(self.line_4, 2, 3, 2, 1)
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setStyleSheet("background-color: #000000;")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout.addWidget(self.line_3, 2, 1, 2, 1)
        self.horizontalLayout.addLayout(self.gridLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 851, 21))
        self.menubar.setStyleSheet("QMenuBar {\n"
"    background-color: #444444;\n"
"    color: #ffffff;\n"
"}\n"
"\n"
"QMenuBar:item:selected {\n"
"    background-color: #555555;\n"
"    color: #ffffff;\n"
"}")
        self.menubar.setObjectName("menubar")
        self.menuAdd_task = QtWidgets.QMenu(self.menubar)
        self.menuAdd_task.setStyleSheet(" QMenu {\n"
"     background-color: #666666;\n"
"     border: 1px solid black;\n"
" }\n"
"\n"
" QMenu:item {\n"
"     background-color: transparent;\n"
"     color: #ffffff;\n"
" }\n"
"\n"
" QMenu:item:selected { \n"
"     background-color: #777777;\n"
" }")
        self.menuAdd_task.setObjectName("menuAdd_task")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setStyleSheet(" QMenu {\n"
"     background-color: #666666;\n"
"     border: 1px solid black;\n"
" }\n"
"\n"
" QMenu:item {\n"
"     background-color: transparent;\n"
"     color: #ffffff;\n"
" }\n"
"\n"
" QMenu:item:selected { \n"
"     background-color: #777777;\n"
" }")
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.actionzz = QtWidgets.QAction(MainWindow)
        self.actionzz.setObjectName("actionzz")
        self.actionAdd_task = QtWidgets.QAction(MainWindow)
        self.actionAdd_task.setObjectName("actionAdd_task")
        self.actionShow_statistics = QtWidgets.QAction(MainWindow)
        self.actionShow_statistics.setObjectName("actionShow_statistics")
        self.menuAdd_task.addAction(self.actionAdd_task)
        self.menu.addAction(self.actionShow_statistics)
        self.menubar.addAction(self.menuAdd_task.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Kaban"))
        self.label.setText(_translate("MainWindow", "Ожидание"))
        self.label_2.setText(_translate("MainWindow", "Работа в процессе"))
        self.label_3.setText(_translate("MainWindow", "Завершенная работа"))
        self.menuAdd_task.setTitle(_translate("MainWindow", "Задача"))
        self.menu.setTitle(_translate("MainWindow", "Статистика"))
        self.actionzz.setText(_translate("MainWindow", "zz"))
        self.actionAdd_task.setText(_translate("MainWindow", "Добавить задачу"))
        self.actionShow_statistics.setText(_translate("MainWindow", "Узнать статистику"))
